name: autoblack
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.2
        uses: actions/setup-python@v1
        with:
           ref: ${{ github.head_ref }}
       - name: Install Black
        run: pip install black
      - name: Run black --check .
        run: black --check .
      - name: If needed, commit black changes to the pull request
        if: failure()
        run:
          black .
          git config --global user.name 'autoblack'
          git config --global user.email 'fredsignupemail@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git commit -am "AutoFormat Python code with Black"
          git push
